// <auto-generated />
using Dev_Assignment.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dev_Assignment.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230309002231_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Dev_Assignment.DAL.Models.InsuredItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("catagoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InsuredItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TV",
                            catagoryId = 1,
                            value = 2500
                        },
                        new
                        {
                            Id = 2,
                            Name = "Playstation 5",
                            catagoryId = 1,
                            value = 500
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laptop",
                            catagoryId = 1,
                            value = 1500
                        },
                        new
                        {
                            Id = 4,
                            Name = "Electric guitar",
                            catagoryId = 1,
                            value = 4000
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shoes",
                            catagoryId = 2,
                            value = 100
                        },
                        new
                        {
                            Id = 6,
                            Name = "Suit",
                            catagoryId = 2,
                            value = 2000
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jacket",
                            catagoryId = 2,
                            value = 400
                        },
                        new
                        {
                            Id = 8,
                            Name = "Oven",
                            catagoryId = 3,
                            value = 2200
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dishwasher",
                            catagoryId = 3,
                            value = 1500
                        },
                        new
                        {
                            Id = 10,
                            Name = "Microwave",
                            catagoryId = 3,
                            value = 790
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
